---

stages:
  - Lint
  - Test
  - Build
  # - Final_Test
  # - Upload

.lint:
  stage: Lint
  image: gacybercenter/gacyber-lint:latest
  # tags:
  #   - docker

mypy:
  extends: .lint
  script: |
    python3 -m mypy . --ignore-missing-imports
  allow_failure: true

flake8:
  extends: .lint
  script: |
    flake8 --ignore=F841
  allow_failure: true

pylint:
  extends: .lint
  script: |
    pylint -d C0301 *.py
    pylint -d C0301 ./image_baker/*.py
  allow_failure: true

yamllint:
  extends: .lint
  script: |
    yamllint -c .yamllint.yml  .
  allow_failure: true

dockerlint:
  extends: .lint
  script: |
    dockerlint
 
.test:
  stage: Test
  image: gacybercenter/image-bakery:latest
  # tags:
  #   - docker

minio_create_bucket:
  stage: Test
  # tags:
  #   - docker
  script: |
    ./mc --version
    ./mc config host add myminio $MINIO_URL $MINIO_A_KEY $MINIO_S_KEY
    ./mc mb myminio/images
  allow_failure: true


minio_avail:
  extends: .test
  script: |
    ./mc config host add myminio $MINIO_URL $MINIO_A_KEY $MINIO_S_KEY
    ./mc ls myminio/images

minio_del_images:
  extends: .test
  script: |
    ./mc config host add myminio $MINIO_URL $MINIO_A_KEY $MINIO_S_KEY
    ./mc ls myminio/images
    ./mc ls myminio/images | awk '{print $5}' > image_list.txt
    while read i; do ./mc rm myminio/images/$i; done < image_list.txt
    ./mc ls myminio/images
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /delete_images/

.build:
  stage: Build
  image: gacybercenter/image-bakery:latest
  tags:
    - docker

build_all:
  extends: .build
  script: |
    python3 image_bake.py $MINIO_ADDR $MINIO_A_KEY $MINIO_S_KEY
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /build_all/
  artifacts:
    when: on_success
    paths:
      - images/
    untracked: true
    expire_in: 2 days

# .final_test:
#   stage: Final_Test
#   image: gacybercenter/image-bakery:latest
#   tags:
#     - docker

# minio_img_verify:
#   extends: .final_test
#   script: |
#     ./mc config host add myminio $MINIO_URL $MINIO_A_KEY $MINIO_S_KEY
#     ./mc ls myminio/images > minio_image_inventory.txt
#   artifacts:
#     when: on_success
#     paths:
#       - minio_image_inventory.txt
#     untracked: true
#     expire_in: 2 weeks

# miniotest:
#   stage: Test
#   tags:
#     - docker
#   script: |
#     apt-get install wget -y
#     wget https://dl.min.io/client/mc/release/linux-amd64/mc
#     chmod +x mc
#     ./mc --version
#     ./mc config host add myminio $MINIO_URL $MINIO_A_KEY $MINIO_S_KEY
#     #./mc mb myminio/images
#     ./mc ls myminio/images
#   allow_failure: true

# .upload:
#   stage: Upload
#   image: gacybercenter/image-bakery:latest
#   script: |
#     echo $SHELL
#     ls -la
#     pwd


