images:
  tags:
    - docker
  image: debian:latest
  script: |
      apt-get -qq update
      apt-get -qq install python3-pip sudo procps yum yum-utils curl qemu-utils kpartx
      pip3 install diskimage-builder
      ### quick test - make real format later
      export DIB_RELEASE=8;disk-image-create -o centos8.raw -t raw centos vm stable-interface-names
  artifacts:
    untracked: true
    when: on_success
    expire_in: 1 day