images:
  tags:
    - docker
  image: gacybercenter/bakery-image:latest
  script: |
      ### quick test - make real format later using yaml descriptor
      apt-get -qq update
      apt-get -qq install jq
      ### centos-8
      virt-builder centos-8.0 --install cloud-init --output centos8.raw
      xz -zT 0 centos8.raw
      auth_string=$(echo -n $B2_APPLICATION_KEY_ID:$B2_APPLICATION_KEY|base64)
      read auth_token apiUrl < <(echo $(curl https://api.backblazeb2.com/b2api/v2/b2_authorize_account -H "Authorization: Basic $auth_string" | jq -r '.authorizationToken, .apiUrl'))
      read upload_auth_token uploadUrl < <(echo $(curl $apiUrl/b2api/v2/b2_get_upload_url -H "Authorization: $auth_token" -d '{"bucketId": "'"$B2_BAKERY_BUCKET_ID"'"}' | jq -r '.authorizationToken, .uploadUrl'))
      curl -H "Authorization: $upload_auth_token" \
      -H "X-Bz-File-Name: centos8.raw.xz" \
      -H "Content-Type: application/octet-stream" \
      -H "X-Bz-Content-Sha1: $(openssl dgst -sha1 centos8.raw.xz | awk '{print $2;}')" \
      -H "X-Bz-Info-Author: unknown" \
      --data-binary "@centos8.raw.xz" \
      $uploadUrl
      ### debian-lxqt
      virt-builder debian-10 --install cloud-init,lxqt --output debian-lxqt.raw --run-command "sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/' /etc/default/grub && update-grub"
      xz -zT 0 debian-lxqt.raw
      auth_string=$(echo -n $B2_APPLICATION_KEY_ID:$B2_APPLICATION_KEY|base64)
      read auth_token apiUrl < <(echo $(curl https://api.backblazeb2.com/b2api/v2/b2_authorize_account -H "Authorization: Basic $auth_string" | jq -r '.authorizationToken, .apiUrl'))
      read upload_auth_token uploadUrl < <(echo $(curl $apiUrl/b2api/v2/b2_get_upload_url -H "Authorization: $auth_token" -d '{"bucketId": "'"$B2_BAKERY_BUCKET_ID"'"}' | jq -r '.authorizationToken, .uploadUrl'))
      curl -H "Authorization: $upload_auth_token" \
      -H "X-Bz-File-Name: debian-lxqt.raw.xz" \
      -H "Content-Type: application/octet-stream" \
      -H "X-Bz-Content-Sha1: $(openssl dgst -sha1 debian-lxqt.raw.xz | awk '{print $2;}')" \
      -H "X-Bz-Info-Author: unknown" \
      --data-binary "@debian-lxqt.raw.xz" \
      $uploadUrl
