images:
  image: debian:latest
  script: |
      apt-get -qq update
      apt-get -qq install python3-pip sudo procps yum yum-utils
      pip3 install diskimage-builder
      ### quick test - make real format later
      export DIB_RELEASE=8;disk-image-create --min-tmpfs 3 -o centos8.raw -t raw centos vm stable-interface-names
  artifacts:
    untracked: true