---

default:
  image: gacybercenter/gacyber-lint:latest
  tags:
    - docker

stages:
  - Static Analysis
  - Test
  - Build

mypy:
  stage: Static Analysis
  script: |
    pwd
    ls -l
    python3 -m mypy ./image_baker --ignore-missing-imports
  allow_failure: true

flake8:
  stage: Static Analysis
  script: |
    flake8 --max-line-length=120 ./image_baker
  allow_failure: true

pylint:
  stage: Static Analysis
  script: |
    pylint -d C0301 ./image_baker
  allow_failure: true

yamllint:
  stage: Static Analysis
  script: |
    yamllint -c .yamllint.yml  .
  allow_failure: true

dockerlint:
  stage: Static Analysis
  script: |
    dockerlint
  allow_failure: true

build:
  image: gophernet/netcat:latest
  tags:
    - docker
  stage: Build
  script: |
    nc localhost 9000
    echo -e "\n"
  allow_failure: true