images:
  tags:
    - docker
  image: gacybercenter/bakery-image:latest
  script: |
      ### quick test - make real format later using yaml descriptor
      apt-get -qq update
      apt-get -qq install jq
      #virt-builder centos-8.0 --install cloud-init --output centos8.raw
      #xz -zT 0 centos8.raw
      dd if=/dev/zero of=./centos8.raw.xz bs=1M count=10
      auth_string=$(echo -n $B2_APPLICATION_KEY_ID:$B2_APPLICATION_KEY|base64)
      read auth_token apiUrl < <(echo $(curl https://api.backblazeb2.com/b2api/v2/b2_authorize_account -H "Authorization: Basic $auth_string" | jq -r '.authorizationToken, .apiUrl'))
      curl $apiUrl/b2api/v2/b2_get_upload_url -H "Authorization: $auth_token" -d '{"bucketId": "'"$B2_BAKERY_BUCKET_ID"'"}'
      echo $uploadUrl
      echo $apiUrl
      curl -H "Authorization: $upload_auth_token" \
      -H "X-Bz-File-Name: centos8.raw.xz" \
      -H "Content-Type: application/octet-stream" \
      -H "X-Bz-Content-Sha1: $(openssl dgst -sha1 centos8.raw.xz | awk '{print $2;}')" \
      -H "X-Bz-Info-Author: unknown" \
      --data-binary "@centos8.raw.xz" \
      $uploadUrl