images:
  tags:
    - docker
  image: gacybercenter/bakery-image:latest
  script: |
      ### quick test - make real format later
      ### note that these jobs must be run in a privileged container with all caps
      apt-get -qq install libguestfs-tools
      virt-builder centos-8.0 --install cloud-init --format raw
  artifacts:
    untracked: true
    when: on_success
    expire_in: 1 day