---

default:
  image: gacybercenter/gacyber-lint:latest
  tags:
    - docker

stages:
  - Static Analysis
  - Test
  - Build

mypy:
  stage: Static Analysis
  script: |
    pwd
    ls -l
    python3 -m mypy ./image_baker
  allow_failure: true

flake8:
  stage: Static Analysis
  script: |
    flake8 --max-line-length=120 ./image_baker
  allow_failure: true

pylint:
  stage: Static Analysis
  script: |
    pylint -d C0301 ./image_baker
  allow_failure: true

yamllint:
  stage: Static Analysis
  script: |
    yamlllint -c .yamllint.yml  .
  allow_failure: true

dockerlint:
  stage: Static Analysis
  script: |
    dockerlint
  allow_failure: true

# convert_uncompress:
#   stage: Build
#   script: |
#       python3 scripts/image_base.py
#   allow_failure: true

# modification:
#   stage: Build
#   script: |
#       python3 scripts/image_mod.py
#   allow_failure: true
